### ISSUE TITLE
Add escape key functionality to close the Modal

### ISSUE THREAD

**Issue by thiago-rocha** [deprecate/metal-modal#1]

**Comment by eduardolundgren** [comment]
How is that going?

**Comment by thiago-rocha** [comment]
I'm already finished but I created a flag to control this feature. What you think, can I send like this?

**Comment by eduardolundgren** [comment]
Yep, a flag is fine. Call it `closeOnEscape`.

**Comment by thiago-rocha** [comment]
https://github.com/metal/crystal-modal/pull/2
